version: "3.6"
services:
  drupal:
    build: ./drupal7
    ports: 
      - 8001:80
    depends_on: 
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
